#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmaderAd.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AmaderAd")]
	public partial class ShodypatiDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBannerImageTbl(BannerImageTbl instance);
    partial void UpdateBannerImageTbl(BannerImageTbl instance);
    partial void DeleteBannerImageTbl(BannerImageTbl instance);
    partial void InsertBannerTbl(BannerTbl instance);
    partial void UpdateBannerTbl(BannerTbl instance);
    partial void DeleteBannerTbl(BannerTbl instance);
    partial void InsertCustomerSearchTbl(CustomerSearchTbl instance);
    partial void UpdateCustomerSearchTbl(CustomerSearchTbl instance);
    partial void DeleteCustomerSearchTbl(CustomerSearchTbl instance);
    partial void InsertLogTbl(LogTbl instance);
    partial void UpdateLogTbl(LogTbl instance);
    partial void DeleteLogTbl(LogTbl instance);
    partial void InsertUserTbl(UserTbl instance);
    partial void UpdateUserTbl(UserTbl instance);
    partial void DeleteUserTbl(UserTbl instance);
    partial void InsertNewspaperTbl(NewspaperTbl instance);
    partial void UpdateNewspaperTbl(NewspaperTbl instance);
    partial void DeleteNewspaperTbl(NewspaperTbl instance);
    #endregion
		
		public ShodypatiDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["AmaderAdConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ShodypatiDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ShodypatiDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ShodypatiDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ShodypatiDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BannerImageTbl> BannerImageTbls
		{
			get
			{
				return this.GetTable<BannerImageTbl>();
			}
		}
		
		public System.Data.Linq.Table<BannerTbl> BannerTbls
		{
			get
			{
				return this.GetTable<BannerTbl>();
			}
		}
		
		public System.Data.Linq.Table<CustomerSearchTbl> CustomerSearchTbls
		{
			get
			{
				return this.GetTable<CustomerSearchTbl>();
			}
		}
		
		public System.Data.Linq.Table<GeoZoneTbl> GeoZoneTbls
		{
			get
			{
				return this.GetTable<GeoZoneTbl>();
			}
		}
		
		public System.Data.Linq.Table<LogTbl> LogTbls
		{
			get
			{
				return this.GetTable<LogTbl>();
			}
		}
		
		public System.Data.Linq.Table<UserTbl> UserTbls
		{
			get
			{
				return this.GetTable<UserTbl>();
			}
		}
		
		public System.Data.Linq.Table<NewspaperTbl> NewspaperTbls
		{
			get
			{
				return this.GetTable<NewspaperTbl>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BannerImageTbl")]
	public partial class BannerImageTbl : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _URL;
		
		private string _ImagePath;
		
		private string _Description;
		
		private System.Nullable<int> _DisplayOrder;
		
		private System.Nullable<int> _MerchantId;
		
		private System.Nullable<int> _CategoryId;
		
		private System.Guid _BannerGuidId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnURLChanging(string value);
    partial void OnURLChanged();
    partial void OnImagePathChanging(string value);
    partial void OnImagePathChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnDisplayOrderChanging(System.Nullable<int> value);
    partial void OnDisplayOrderChanged();
    partial void OnMerchantIdChanging(System.Nullable<int> value);
    partial void OnMerchantIdChanged();
    partial void OnCategoryIdChanging(System.Nullable<int> value);
    partial void OnCategoryIdChanged();
    partial void OnBannerGuidIdChanging(System.Guid value);
    partial void OnBannerGuidIdChanged();
    #endregion
		
		public BannerImageTbl()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URL", DbType="NVarChar(256)")]
		public string URL
		{
			get
			{
				return this._URL;
			}
			set
			{
				if ((this._URL != value))
				{
					this.OnURLChanging(value);
					this.SendPropertyChanging();
					this._URL = value;
					this.SendPropertyChanged("URL");
					this.OnURLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImagePath", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string ImagePath
		{
			get
			{
				return this._ImagePath;
			}
			set
			{
				if ((this._ImagePath != value))
				{
					this.OnImagePathChanging(value);
					this.SendPropertyChanging();
					this._ImagePath = value;
					this.SendPropertyChanged("ImagePath");
					this.OnImagePathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(256)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayOrder", DbType="Int")]
		public System.Nullable<int> DisplayOrder
		{
			get
			{
				return this._DisplayOrder;
			}
			set
			{
				if ((this._DisplayOrder != value))
				{
					this.OnDisplayOrderChanging(value);
					this.SendPropertyChanging();
					this._DisplayOrder = value;
					this.SendPropertyChanged("DisplayOrder");
					this.OnDisplayOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MerchantId", DbType="Int")]
		public System.Nullable<int> MerchantId
		{
			get
			{
				return this._MerchantId;
			}
			set
			{
				if ((this._MerchantId != value))
				{
					this.OnMerchantIdChanging(value);
					this.SendPropertyChanging();
					this._MerchantId = value;
					this.SendPropertyChanged("MerchantId");
					this.OnMerchantIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryId", DbType="Int")]
		public System.Nullable<int> CategoryId
		{
			get
			{
				return this._CategoryId;
			}
			set
			{
				if ((this._CategoryId != value))
				{
					this.OnCategoryIdChanging(value);
					this.SendPropertyChanging();
					this._CategoryId = value;
					this.SendPropertyChanged("CategoryId");
					this.OnCategoryIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BannerGuidId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid BannerGuidId
		{
			get
			{
				return this._BannerGuidId;
			}
			set
			{
				if ((this._BannerGuidId != value))
				{
					this.OnBannerGuidIdChanging(value);
					this.SendPropertyChanging();
					this._BannerGuidId = value;
					this.SendPropertyChanged("BannerGuidId");
					this.OnBannerGuidIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BannerTbl")]
	public partial class BannerTbl : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Name;
		
		private System.Nullable<System.DateTime> _CreatedOnUtc;
		
		private System.Nullable<System.DateTime> _UpdatedOnUtc;
		
		private System.Nullable<bool> _Published;
		
		private System.Guid _GuidId;
		
		private System.Nullable<bool> _IsHomePageBanner;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnCreatedOnUtcChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedOnUtcChanged();
    partial void OnUpdatedOnUtcChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdatedOnUtcChanged();
    partial void OnPublishedChanging(System.Nullable<bool> value);
    partial void OnPublishedChanged();
    partial void OnGuidIdChanging(System.Guid value);
    partial void OnGuidIdChanged();
    partial void OnIsHomePageBannerChanging(System.Nullable<bool> value);
    partial void OnIsHomePageBannerChanged();
    #endregion
		
		public BannerTbl()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(256)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOnUtc", DbType="DateTime2")]
		public System.Nullable<System.DateTime> CreatedOnUtc
		{
			get
			{
				return this._CreatedOnUtc;
			}
			set
			{
				if ((this._CreatedOnUtc != value))
				{
					this.OnCreatedOnUtcChanging(value);
					this.SendPropertyChanging();
					this._CreatedOnUtc = value;
					this.SendPropertyChanged("CreatedOnUtc");
					this.OnCreatedOnUtcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedOnUtc", DbType="DateTime2")]
		public System.Nullable<System.DateTime> UpdatedOnUtc
		{
			get
			{
				return this._UpdatedOnUtc;
			}
			set
			{
				if ((this._UpdatedOnUtc != value))
				{
					this.OnUpdatedOnUtcChanging(value);
					this.SendPropertyChanging();
					this._UpdatedOnUtc = value;
					this.SendPropertyChanged("UpdatedOnUtc");
					this.OnUpdatedOnUtcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Published", DbType="Bit")]
		public System.Nullable<bool> Published
		{
			get
			{
				return this._Published;
			}
			set
			{
				if ((this._Published != value))
				{
					this.OnPublishedChanging(value);
					this.SendPropertyChanging();
					this._Published = value;
					this.SendPropertyChanged("Published");
					this.OnPublishedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GuidId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid GuidId
		{
			get
			{
				return this._GuidId;
			}
			set
			{
				if ((this._GuidId != value))
				{
					this.OnGuidIdChanging(value);
					this.SendPropertyChanging();
					this._GuidId = value;
					this.SendPropertyChanged("GuidId");
					this.OnGuidIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsHomePageBanner", DbType="Bit")]
		public System.Nullable<bool> IsHomePageBanner
		{
			get
			{
				return this._IsHomePageBanner;
			}
			set
			{
				if ((this._IsHomePageBanner != value))
				{
					this.OnIsHomePageBannerChanging(value);
					this.SendPropertyChanging();
					this._IsHomePageBanner = value;
					this.SendPropertyChanged("IsHomePageBanner");
					this.OnIsHomePageBannerChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CustomerSearchTbl")]
	public partial class CustomerSearchTbl : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _UserId;
		
		private string _Keyword;
		
		private string _IpAddress;
		
		private System.Nullable<System.DateTime> _CreatedOnUtc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnUserIdChanging(int value);
    partial void OnUserIdChanged();
    partial void OnKeywordChanging(string value);
    partial void OnKeywordChanged();
    partial void OnIpAddressChanging(string value);
    partial void OnIpAddressChanged();
    partial void OnCreatedOnUtcChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedOnUtcChanged();
    #endregion
		
		public CustomerSearchTbl()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Int NOT NULL")]
		public int UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Keyword", DbType="NVarChar(512)")]
		public string Keyword
		{
			get
			{
				return this._Keyword;
			}
			set
			{
				if ((this._Keyword != value))
				{
					this.OnKeywordChanging(value);
					this.SendPropertyChanging();
					this._Keyword = value;
					this.SendPropertyChanged("Keyword");
					this.OnKeywordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IpAddress", DbType="NVarChar(128)")]
		public string IpAddress
		{
			get
			{
				return this._IpAddress;
			}
			set
			{
				if ((this._IpAddress != value))
				{
					this.OnIpAddressChanging(value);
					this.SendPropertyChanging();
					this._IpAddress = value;
					this.SendPropertyChanged("IpAddress");
					this.OnIpAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOnUtc", DbType="DateTime2")]
		public System.Nullable<System.DateTime> CreatedOnUtc
		{
			get
			{
				return this._CreatedOnUtc;
			}
			set
			{
				if ((this._CreatedOnUtc != value))
				{
					this.OnCreatedOnUtcChanging(value);
					this.SendPropertyChanging();
					this._CreatedOnUtc = value;
					this.SendPropertyChanged("CreatedOnUtc");
					this.OnCreatedOnUtcChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GeoZoneTbl")]
	public partial class GeoZoneTbl
	{
		
		private int _Id;
		
		private string _Name;
		
		private string _Description;
		
		private System.Nullable<int> _DateAdded;
		
		private System.Nullable<int> _DateModified;
		
		public GeoZoneTbl()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(128)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateAdded", DbType="Int")]
		public System.Nullable<int> DateAdded
		{
			get
			{
				return this._DateAdded;
			}
			set
			{
				if ((this._DateAdded != value))
				{
					this._DateAdded = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateModified", DbType="Int")]
		public System.Nullable<int> DateModified
		{
			get
			{
				return this._DateModified;
			}
			set
			{
				if ((this._DateModified != value))
				{
					this._DateModified = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LogTbl")]
	public partial class LogTbl : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _ExceptionMessage;
		
		private string _ExceptionStackTrace;
		
		private string _ControllerName;
		
		private string _IpAddress;
		
		private string _Browser;
		
		private string _OS;
		
		private System.Nullable<System.Guid> _UserId;
		
		private string _ActionName;
		
		private System.Nullable<System.DateTime> _CreatedOnUtc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnExceptionMessageChanging(string value);
    partial void OnExceptionMessageChanged();
    partial void OnExceptionStackTraceChanging(string value);
    partial void OnExceptionStackTraceChanged();
    partial void OnControllerNameChanging(string value);
    partial void OnControllerNameChanged();
    partial void OnIpAddressChanging(string value);
    partial void OnIpAddressChanged();
    partial void OnBrowserChanging(string value);
    partial void OnBrowserChanged();
    partial void OnOSChanging(string value);
    partial void OnOSChanged();
    partial void OnUserIdChanging(System.Nullable<System.Guid> value);
    partial void OnUserIdChanged();
    partial void OnActionNameChanging(string value);
    partial void OnActionNameChanged();
    partial void OnCreatedOnUtcChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedOnUtcChanged();
    #endregion
		
		public LogTbl()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExceptionMessage", DbType="NVarChar(3050)")]
		public string ExceptionMessage
		{
			get
			{
				return this._ExceptionMessage;
			}
			set
			{
				if ((this._ExceptionMessage != value))
				{
					this.OnExceptionMessageChanging(value);
					this.SendPropertyChanging();
					this._ExceptionMessage = value;
					this.SendPropertyChanged("ExceptionMessage");
					this.OnExceptionMessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExceptionStackTrace", DbType="NVarChar(MAX)")]
		public string ExceptionStackTrace
		{
			get
			{
				return this._ExceptionStackTrace;
			}
			set
			{
				if ((this._ExceptionStackTrace != value))
				{
					this.OnExceptionStackTraceChanging(value);
					this.SendPropertyChanging();
					this._ExceptionStackTrace = value;
					this.SendPropertyChanged("ExceptionStackTrace");
					this.OnExceptionStackTraceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ControllerName", DbType="NVarChar(256)")]
		public string ControllerName
		{
			get
			{
				return this._ControllerName;
			}
			set
			{
				if ((this._ControllerName != value))
				{
					this.OnControllerNameChanging(value);
					this.SendPropertyChanging();
					this._ControllerName = value;
					this.SendPropertyChanged("ControllerName");
					this.OnControllerNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IpAddress", DbType="NVarChar(256)")]
		public string IpAddress
		{
			get
			{
				return this._IpAddress;
			}
			set
			{
				if ((this._IpAddress != value))
				{
					this.OnIpAddressChanging(value);
					this.SendPropertyChanging();
					this._IpAddress = value;
					this.SendPropertyChanged("IpAddress");
					this.OnIpAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Browser", DbType="NVarChar(3050)")]
		public string Browser
		{
			get
			{
				return this._Browser;
			}
			set
			{
				if ((this._Browser != value))
				{
					this.OnBrowserChanging(value);
					this.SendPropertyChanging();
					this._Browser = value;
					this.SendPropertyChanged("Browser");
					this.OnBrowserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OS", DbType="NVarChar(256)")]
		public string OS
		{
			get
			{
				return this._OS;
			}
			set
			{
				if ((this._OS != value))
				{
					this.OnOSChanging(value);
					this.SendPropertyChanging();
					this._OS = value;
					this.SendPropertyChanged("OS");
					this.OnOSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActionName", DbType="NVarChar(256)")]
		public string ActionName
		{
			get
			{
				return this._ActionName;
			}
			set
			{
				if ((this._ActionName != value))
				{
					this.OnActionNameChanging(value);
					this.SendPropertyChanging();
					this._ActionName = value;
					this.SendPropertyChanged("ActionName");
					this.OnActionNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOnUtc", DbType="DateTime2")]
		public System.Nullable<System.DateTime> CreatedOnUtc
		{
			get
			{
				return this._CreatedOnUtc;
			}
			set
			{
				if ((this._CreatedOnUtc != value))
				{
					this.OnCreatedOnUtcChanging(value);
					this.SendPropertyChanging();
					this._CreatedOnUtc = value;
					this.SendPropertyChanged("CreatedOnUtc");
					this.OnCreatedOnUtcChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserTbl")]
	public partial class UserTbl : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _Company;
		
		private System.Nullable<int> _NoOfVisits;
		
		private System.Nullable<System.DateTime> _LastLoginDateUtc;
		
		private string _LastLoginIP;
		
		private System.Nullable<int> _FailedLoginAttempts;
		
		private System.Nullable<System.DateTime> _CannotLoginUntilDateUtc;
		
		private System.Nullable<System.DateTime> _CreatedOnUtc;
		
		private System.Nullable<System.DateTime> _UpdatedOnUtc;
		
		private System.Nullable<bool> _Active;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnCompanyChanging(string value);
    partial void OnCompanyChanged();
    partial void OnNoOfVisitsChanging(System.Nullable<int> value);
    partial void OnNoOfVisitsChanged();
    partial void OnLastLoginDateUtcChanging(System.Nullable<System.DateTime> value);
    partial void OnLastLoginDateUtcChanged();
    partial void OnLastLoginIPChanging(string value);
    partial void OnLastLoginIPChanged();
    partial void OnFailedLoginAttemptsChanging(System.Nullable<int> value);
    partial void OnFailedLoginAttemptsChanged();
    partial void OnCannotLoginUntilDateUtcChanging(System.Nullable<System.DateTime> value);
    partial void OnCannotLoginUntilDateUtcChanged();
    partial void OnCreatedOnUtcChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedOnUtcChanged();
    partial void OnUpdatedOnUtcChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdatedOnUtcChanged();
    partial void OnActiveChanging(System.Nullable<bool> value);
    partial void OnActiveChanged();
    #endregion
		
		public UserTbl()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(128)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(128)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company", DbType="NVarChar(128)")]
		public string Company
		{
			get
			{
				return this._Company;
			}
			set
			{
				if ((this._Company != value))
				{
					this.OnCompanyChanging(value);
					this.SendPropertyChanging();
					this._Company = value;
					this.SendPropertyChanged("Company");
					this.OnCompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoOfVisits", DbType="Int")]
		public System.Nullable<int> NoOfVisits
		{
			get
			{
				return this._NoOfVisits;
			}
			set
			{
				if ((this._NoOfVisits != value))
				{
					this.OnNoOfVisitsChanging(value);
					this.SendPropertyChanging();
					this._NoOfVisits = value;
					this.SendPropertyChanged("NoOfVisits");
					this.OnNoOfVisitsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastLoginDateUtc", DbType="DateTime2")]
		public System.Nullable<System.DateTime> LastLoginDateUtc
		{
			get
			{
				return this._LastLoginDateUtc;
			}
			set
			{
				if ((this._LastLoginDateUtc != value))
				{
					this.OnLastLoginDateUtcChanging(value);
					this.SendPropertyChanging();
					this._LastLoginDateUtc = value;
					this.SendPropertyChanged("LastLoginDateUtc");
					this.OnLastLoginDateUtcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastLoginIP", DbType="NVarChar(128)")]
		public string LastLoginIP
		{
			get
			{
				return this._LastLoginIP;
			}
			set
			{
				if ((this._LastLoginIP != value))
				{
					this.OnLastLoginIPChanging(value);
					this.SendPropertyChanging();
					this._LastLoginIP = value;
					this.SendPropertyChanged("LastLoginIP");
					this.OnLastLoginIPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FailedLoginAttempts", DbType="Int")]
		public System.Nullable<int> FailedLoginAttempts
		{
			get
			{
				return this._FailedLoginAttempts;
			}
			set
			{
				if ((this._FailedLoginAttempts != value))
				{
					this.OnFailedLoginAttemptsChanging(value);
					this.SendPropertyChanging();
					this._FailedLoginAttempts = value;
					this.SendPropertyChanged("FailedLoginAttempts");
					this.OnFailedLoginAttemptsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CannotLoginUntilDateUtc", DbType="DateTime2")]
		public System.Nullable<System.DateTime> CannotLoginUntilDateUtc
		{
			get
			{
				return this._CannotLoginUntilDateUtc;
			}
			set
			{
				if ((this._CannotLoginUntilDateUtc != value))
				{
					this.OnCannotLoginUntilDateUtcChanging(value);
					this.SendPropertyChanging();
					this._CannotLoginUntilDateUtc = value;
					this.SendPropertyChanged("CannotLoginUntilDateUtc");
					this.OnCannotLoginUntilDateUtcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOnUtc", DbType="DateTime2")]
		public System.Nullable<System.DateTime> CreatedOnUtc
		{
			get
			{
				return this._CreatedOnUtc;
			}
			set
			{
				if ((this._CreatedOnUtc != value))
				{
					this.OnCreatedOnUtcChanging(value);
					this.SendPropertyChanging();
					this._CreatedOnUtc = value;
					this.SendPropertyChanged("CreatedOnUtc");
					this.OnCreatedOnUtcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedOnUtc", DbType="DateTime2")]
		public System.Nullable<System.DateTime> UpdatedOnUtc
		{
			get
			{
				return this._UpdatedOnUtc;
			}
			set
			{
				if ((this._UpdatedOnUtc != value))
				{
					this.OnUpdatedOnUtcChanging(value);
					this.SendPropertyChanging();
					this._UpdatedOnUtc = value;
					this.SendPropertyChanged("UpdatedOnUtc");
					this.OnUpdatedOnUtcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
		public System.Nullable<bool> Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NewspaperTbl")]
	public partial class NewspaperTbl : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<System.Guid> _NewsGuidId;
		
		private string _NewspaperName;
		
		private string _AdLocation;
		
		private System.Nullable<int> _Price;
		
		private string _AdvertiserName;
		
		private string _AdvertiserAddress;
		
		private string _AdvertiserMobile;
		
		private string _AdvertiserEmail;
		
		private System.Nullable<System.DateTime> _DateofPublication;
		
		private System.Nullable<int> _ColumnSize;
		
		private System.Nullable<int> _Inch;
		
		private System.Nullable<int> _TotalColumnInch;
		
		private System.Nullable<int> _TotalPrice;
		
		private string _AllAdCategoryId;
		
		private string _Description;
		
		private string _MainImagePath;
		
		private System.Nullable<System.DateTime> _CreatedOnUtc;
		
		private System.Nullable<System.DateTime> _UpdatedOnUtc;
		
		private System.Nullable<bool> _Active;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNewsGuidIdChanging(System.Nullable<System.Guid> value);
    partial void OnNewsGuidIdChanged();
    partial void OnNewspaperNameChanging(string value);
    partial void OnNewspaperNameChanged();
    partial void OnAdLocationChanging(string value);
    partial void OnAdLocationChanged();
    partial void OnPriceChanging(System.Nullable<int> value);
    partial void OnPriceChanged();
    partial void OnAdvertiserNameChanging(string value);
    partial void OnAdvertiserNameChanged();
    partial void OnAdvertiserAddressChanging(string value);
    partial void OnAdvertiserAddressChanged();
    partial void OnAdvertiserMobileChanging(string value);
    partial void OnAdvertiserMobileChanged();
    partial void OnAdvertiserEmailChanging(string value);
    partial void OnAdvertiserEmailChanged();
    partial void OnDateofPublicationChanging(System.Nullable<System.DateTime> value);
    partial void OnDateofPublicationChanged();
    partial void OnColumnSizeChanging(System.Nullable<int> value);
    partial void OnColumnSizeChanged();
    partial void OnInchChanging(System.Nullable<int> value);
    partial void OnInchChanged();
    partial void OnTotalColumnInchChanging(System.Nullable<int> value);
    partial void OnTotalColumnInchChanged();
    partial void OnTotalPriceChanging(System.Nullable<int> value);
    partial void OnTotalPriceChanged();
    partial void OnAllAdCategoryIdChanging(string value);
    partial void OnAllAdCategoryIdChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnMainImagePathChanging(string value);
    partial void OnMainImagePathChanged();
    partial void OnCreatedOnUtcChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedOnUtcChanged();
    partial void OnUpdatedOnUtcChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdatedOnUtcChanged();
    partial void OnActiveChanging(System.Nullable<bool> value);
    partial void OnActiveChanged();
    #endregion
		
		public NewspaperTbl()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsGuidId", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> NewsGuidId
		{
			get
			{
				return this._NewsGuidId;
			}
			set
			{
				if ((this._NewsGuidId != value))
				{
					this.OnNewsGuidIdChanging(value);
					this.SendPropertyChanging();
					this._NewsGuidId = value;
					this.SendPropertyChanged("NewsGuidId");
					this.OnNewsGuidIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewspaperName", DbType="NVarChar(255)")]
		public string NewspaperName
		{
			get
			{
				return this._NewspaperName;
			}
			set
			{
				if ((this._NewspaperName != value))
				{
					this.OnNewspaperNameChanging(value);
					this.SendPropertyChanging();
					this._NewspaperName = value;
					this.SendPropertyChanged("NewspaperName");
					this.OnNewspaperNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdLocation", DbType="NVarChar(1020)")]
		public string AdLocation
		{
			get
			{
				return this._AdLocation;
			}
			set
			{
				if ((this._AdLocation != value))
				{
					this.OnAdLocationChanging(value);
					this.SendPropertyChanging();
					this._AdLocation = value;
					this.SendPropertyChanged("AdLocation");
					this.OnAdLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Int")]
		public System.Nullable<int> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdvertiserName", DbType="NVarChar(255)")]
		public string AdvertiserName
		{
			get
			{
				return this._AdvertiserName;
			}
			set
			{
				if ((this._AdvertiserName != value))
				{
					this.OnAdvertiserNameChanging(value);
					this.SendPropertyChanging();
					this._AdvertiserName = value;
					this.SendPropertyChanged("AdvertiserName");
					this.OnAdvertiserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdvertiserAddress", DbType="NVarChar(255)")]
		public string AdvertiserAddress
		{
			get
			{
				return this._AdvertiserAddress;
			}
			set
			{
				if ((this._AdvertiserAddress != value))
				{
					this.OnAdvertiserAddressChanging(value);
					this.SendPropertyChanging();
					this._AdvertiserAddress = value;
					this.SendPropertyChanged("AdvertiserAddress");
					this.OnAdvertiserAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdvertiserMobile", DbType="NVarChar(20)")]
		public string AdvertiserMobile
		{
			get
			{
				return this._AdvertiserMobile;
			}
			set
			{
				if ((this._AdvertiserMobile != value))
				{
					this.OnAdvertiserMobileChanging(value);
					this.SendPropertyChanging();
					this._AdvertiserMobile = value;
					this.SendPropertyChanged("AdvertiserMobile");
					this.OnAdvertiserMobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdvertiserEmail", DbType="NVarChar(100)")]
		public string AdvertiserEmail
		{
			get
			{
				return this._AdvertiserEmail;
			}
			set
			{
				if ((this._AdvertiserEmail != value))
				{
					this.OnAdvertiserEmailChanging(value);
					this.SendPropertyChanging();
					this._AdvertiserEmail = value;
					this.SendPropertyChanged("AdvertiserEmail");
					this.OnAdvertiserEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateofPublication", DbType="DateTime2")]
		public System.Nullable<System.DateTime> DateofPublication
		{
			get
			{
				return this._DateofPublication;
			}
			set
			{
				if ((this._DateofPublication != value))
				{
					this.OnDateofPublicationChanging(value);
					this.SendPropertyChanging();
					this._DateofPublication = value;
					this.SendPropertyChanged("DateofPublication");
					this.OnDateofPublicationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ColumnSize", DbType="Int")]
		public System.Nullable<int> ColumnSize
		{
			get
			{
				return this._ColumnSize;
			}
			set
			{
				if ((this._ColumnSize != value))
				{
					this.OnColumnSizeChanging(value);
					this.SendPropertyChanging();
					this._ColumnSize = value;
					this.SendPropertyChanged("ColumnSize");
					this.OnColumnSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Inch", DbType="Int")]
		public System.Nullable<int> Inch
		{
			get
			{
				return this._Inch;
			}
			set
			{
				if ((this._Inch != value))
				{
					this.OnInchChanging(value);
					this.SendPropertyChanging();
					this._Inch = value;
					this.SendPropertyChanged("Inch");
					this.OnInchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalColumnInch", DbType="Int")]
		public System.Nullable<int> TotalColumnInch
		{
			get
			{
				return this._TotalColumnInch;
			}
			set
			{
				if ((this._TotalColumnInch != value))
				{
					this.OnTotalColumnInchChanging(value);
					this.SendPropertyChanging();
					this._TotalColumnInch = value;
					this.SendPropertyChanged("TotalColumnInch");
					this.OnTotalColumnInchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalPrice", DbType="Int")]
		public System.Nullable<int> TotalPrice
		{
			get
			{
				return this._TotalPrice;
			}
			set
			{
				if ((this._TotalPrice != value))
				{
					this.OnTotalPriceChanging(value);
					this.SendPropertyChanging();
					this._TotalPrice = value;
					this.SendPropertyChanged("TotalPrice");
					this.OnTotalPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AllAdCategoryId", DbType="NVarChar(20)")]
		public string AllAdCategoryId
		{
			get
			{
				return this._AllAdCategoryId;
			}
			set
			{
				if ((this._AllAdCategoryId != value))
				{
					this.OnAllAdCategoryIdChanging(value);
					this.SendPropertyChanging();
					this._AllAdCategoryId = value;
					this.SendPropertyChanged("AllAdCategoryId");
					this.OnAllAdCategoryIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(4000)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MainImagePath", DbType="NVarChar(255)")]
		public string MainImagePath
		{
			get
			{
				return this._MainImagePath;
			}
			set
			{
				if ((this._MainImagePath != value))
				{
					this.OnMainImagePathChanging(value);
					this.SendPropertyChanging();
					this._MainImagePath = value;
					this.SendPropertyChanged("MainImagePath");
					this.OnMainImagePathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOnUtc", DbType="DateTime2")]
		public System.Nullable<System.DateTime> CreatedOnUtc
		{
			get
			{
				return this._CreatedOnUtc;
			}
			set
			{
				if ((this._CreatedOnUtc != value))
				{
					this.OnCreatedOnUtcChanging(value);
					this.SendPropertyChanging();
					this._CreatedOnUtc = value;
					this.SendPropertyChanged("CreatedOnUtc");
					this.OnCreatedOnUtcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedOnUtc", DbType="DateTime2")]
		public System.Nullable<System.DateTime> UpdatedOnUtc
		{
			get
			{
				return this._UpdatedOnUtc;
			}
			set
			{
				if ((this._UpdatedOnUtc != value))
				{
					this.OnUpdatedOnUtcChanging(value);
					this.SendPropertyChanging();
					this._UpdatedOnUtc = value;
					this.SendPropertyChanged("UpdatedOnUtc");
					this.OnUpdatedOnUtcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
		public System.Nullable<bool> Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
